In [3]:
import numpy as np

In [4]:
a = np.arange(1,10,dtype='int').reshape(3,3)

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
a[1,2]

np.int64(6)

In [6]:
a[:,1]

array([2, 5, 8])

In [7]:
a[1,]

array([4, 5, 6])

In [8]:
a[1]

array([4, 5, 6])

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [11]:
a = np.arange(1,26).reshape(5,5)

print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [12]:
a[3,4]

np.int64(20)

In [13]:
a[1:3,:4:2]

array([[ 6,  8],
       [11, 13]])

In [14]:
print(a)

b = a[1:4]
b

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
print(b)

c = b[1:3]

c


[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
print(a)

a[1:4,1:3]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 7,  8],
       [12, 13],
       [17, 18]])

In [17]:
a[1:5,3:5]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [18]:
a[1:5,1:2]


array([[ 7],
       [12],
       [17],
       [22]])

In [19]:
a[0:5,2:3]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23]])

In [20]:
a = np.arange(1,28,dtype='int').reshape(3,3,3)

print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [21]:
a[2,2,1]

np.int64(26)

In [22]:
a[1,0,1]

np.int64(11)

In [23]:
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [24]:
a>10

array([[[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [25]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [26]:
a[a<=10] = 8998

print(a)

[[[8998 8998 8998]
  [8998 8998 8998]
  [8998 8998 8998]]

 [[8998   11   12]
  [  13   14   15]
  [  16   17   18]]

 [[  19   20   21]
  [  22   23   24]
  [  25   26   27]]]


In [27]:
np.random.random(5)

array([0.51794593, 0.35558957, 0.84126604, 0.32848019, 0.08589992])

In [28]:
a =np.random.random((3,3))

print(a)

[[0.22273087 0.09134693 0.3990206 ]
 [0.63237812 0.84574458 0.20475944]
 [0.75432596 0.53197128 0.99082585]]


In [29]:
a = np.random.randint(0,10,(2,3,3))

print(a)

[[[0 6 8]
  [4 4 8]
  [3 6 6]]

 [[1 6 2]
  [8 9 2]
  [8 2 6]]]


In [30]:
a = np.random.rand(4,5)
# used for uniform distribution in half-open interval  
print(a)

[[0.67612294 0.58396726 0.49465295 0.74781621 0.31592457]
 [0.43352632 0.6192308  0.97506549 0.76031866 0.10921413]
 [0.32280599 0.6575732  0.46927997 0.87833665 0.41661971]
 [0.23646    0.34348602 0.11465288 0.05466018 0.62213968]]


In [31]:
a = np.random.randn(6,3) 
#gausian distribution for standard normal matrix
print(a)

[[ 0.87733469  0.00805669  0.07274852]
 [ 0.85499889  0.28771694 -0.12884367]
 [-0.10319521  0.40686418 -0.1538736 ]
 [ 0.58025128 -0.66606248 -0.03157349]
 [-1.84236082 -1.20520596  1.29083026]
 [-0.14787882  0.08978766  0.74729286]]


In [39]:
x = [1,2,3,4,4,55,6,7]

np.random.choice(x)

np.int64(3)