In [53]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: C:\Users\sonik\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

In [7]:
one = np.array([1,2,3,4,4,5,6])

print(one)

[1 2 3 4 4 5 6]


In [10]:
two = np.array([[1,2,3,4,4,6],[77,5,3,211,35,6]])

print(two)

[[  1   2   3   4   4   6]
 [ 77   5   3 211  35   6]]


In [13]:
three = np.array([[[123,1123,1212,1212,112],[121,3232,2323,2323,23232],[1,3,4,5,6]]])

print(three)

[[[  123  1123  1212  1212   112]
  [  121  3232  2323  2323 23232]
  [    1     3     4     5     6]]]


In [22]:
three_1 = np.array([[[123,1123,1212,1212,112]],[[121,3232,2323,2323,23232]],[[1,3,4,5,6]]])

print(three_1)

[[[  123  1123  1212  1212   112]]

 [[  121  3232  2323  2323 23232]]

 [[    1     3     4     5     6]]]


In [18]:
one.shape


(7,)

In [20]:
two.shape

(2, 6)

In [24]:
three.shape

(3, 1, 5)

In [26]:
three_1.shape

(3, 1, 5)

In [28]:
one.size

7

In [31]:
two.size

12

In [33]:
three.size

15

In [35]:
one.itemsize

8

In [37]:
one.dtype

dtype('int64')

In [42]:
one1 = one.astype("float")

print(one1)

[1. 2. 3. 4. 4. 5. 6.]


In [49]:
x = np.array([[1,0,3,0,5,0],[1,2,0,4,5,5],[5,4,3,2,0,1]],dtype="bool")

print(x)

[[ True False  True False  True False]
 [ True  True False  True  True  True]
 [ True  True  True  True False  True]]
