In [ ]:
# %pip install numpy
import numpy as np

In [ ]:
#arange function
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [5]:
a = np.arange(0,21,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
#LINSPACE FUNCTION
#Formula ---> i = start+ix   ((stop-start)/num-1)

a = np.linspace(12,96,11)
print(a)

[12.  20.4 28.8 37.2 45.6 54.  62.4 70.8 79.2 87.6 96. ]


In [17]:
a = np.arange(1,41).reshape(2,20)

print(a)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]]


In [18]:
a.reshape(20,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30],
       [31, 32],
       [33, 34],
       [35, 36],
       [37, 38],
       [39, 40]])

In [21]:
a.reshape(5,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40]]])

In [26]:
x = np.arange(10,50).reshape(2,4,5)
print(x)
x.ndim

[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


3

In [27]:
#ravel and flatten are dimension reduction tequnich which convert any dimension it to one dimension.


x = np.arange(1,21).reshape(5,2,2)
print(x)
a = x.ravel()
print("\n")
x[0,0] = 34
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


[34 34  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [28]:
x = np.arange(1,21).reshape(5,2,2)
print(x)
a = x.flatten()
print("\n")
x[0,0] = 34
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [30]:
a = np.arange(1,21).reshape(5,2,2)
a.transpose()
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


In [38]:
a = np.arange(1,21).reshape(5,2,2)
print(a)
a.T

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


array([[[ 1,  5,  9, 13, 17],
        [ 3,  7, 11, 15, 19]],

       [[ 2,  6, 10, 14, 18],
        [ 4,  8, 12, 16, 20]]])

In [ ]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
print(a)
print("\n\n")
print(b)
print("\n\n")
print(a+b)

#np.add(a,b)
#np.subtract(a,b) / print(a-b) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]



[[11 12 13]
 [14 15 16]
 [17 18 19]]



[[12 14 16]
 [18 20 22]
 [24 26 28]]


In [ ]:
print (a@b) 
#print(a/b)

print("\n\n")
print(a*b)

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]



[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [47]:
print(a)
print(b)

a.dot(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [50]:
print(a)

a.sum()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


np.int64(45)

In [52]:
np.sin(30 * np.pi/180)

np.float64(0.49999999999999994)

In [53]:
np.cos(60 * np.pi /180)

np.float64(0.5000000000000001)

In [56]:
np.tan(45 *np.pi /180)

np.float64(0.9999999999999999)

In [51]:
np.sin(90)

np.float64(0.8939966636005579)

In [59]:
x = np.array([[1,2,3,44],[5,6,7,8],[979,454,34,232]])
print(x)

[[  1   2   3  44]
 [  5   6   7   8]
 [979 454  34 232]]


In [60]:
x.argmax()

np.int64(8)

In [61]:
x.min()

np.int64(1)

In [62]:
x.max()

np.int64(979)

In [64]:
x.mean()

np.float64(147.91666666666666)

In [65]:
x.argmin()

np.int64(0)

In [66]:
x.argmin(axis = 1)

array([0, 0, 2])

In [67]:
x.std()

np.float64(282.71141302670395)

In [68]:
np.square(x)

array([[     1,      4,      9,   1936],
       [    25,     36,     49,     64],
       [958441, 206116,   1156,  53824]])

In [69]:
np.sqrt(x)

array([[ 1.        ,  1.41421356,  1.73205081,  6.63324958],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712],
       [31.28897569, 21.30727575,  5.83095189, 15.23154621]])

In [70]:
a = np.nan
print(a)

nan


In [74]:
a = np.arange(1,10,dtype ="int").reshape(3,3)
b = np.arange(11,20,dtype ="int").reshape(3,3)
c = np.arange(21,30,dtype ="int").reshape(3,3)
d = np.arange(31,40,dtype ="int").reshape(3,3)

print(a)
print(b)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [77]:
x = np.hstack((a,b,c,d))
print(x)

[[ 1  2  3 11 12 13 21 22 23 31 32 33]
 [ 4  5  6 14 15 16 24 25 26 34 35 36]
 [ 7  8  9 17 18 19 27 28 29 37 38 39]]


In [81]:
x = np.vstack((a,b,c))
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


In [83]:
e = np.concatenate((a,b,c),axis = 0)
print(e)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


In [92]:
e = np.concatenate((a,b,c),axis = 1)
print(e)

[[ 1  2  3 11 12 13 21 22 23]
 [ 4  5  6 14 15 16 24 25 26]
 [ 7  8  9 17 18 19 27 28 29]]


In [99]:
z = np.split(e,3)

print(z)

[array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23]]), array([[ 4,  5,  6, 14, 15, 16, 24, 25, 26]]), array([[ 7,  8,  9, 17, 18, 19, 27, 28, 29]])]


In [100]:
type(z)

list

In [102]:
y = np.array([1,2,3,4,5,6,7,8,9])

np.split(y,[1,2,3,99])

[array([1]),
 array([2]),
 array([3]),
 array([4, 5, 6, 7, 8, 9]),
 array([], dtype=int64)]